server:
  #context-path: /quartz
  port: 8080
  ession-timeout: 60
#server.address=192.168.1.66

  tomcat:
    max-threads: 100
    uri-encoding: UTF-8

spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    cache-period: 0
    template:
      cache: false
  devtools:
    livereload:
      enabled: true

  mvc:
    static-path-pattern: /**

  datasource:
    url: jdbc:mysql://59.110.169.156:3306/bbd?useSSL=true&autoReconnect=true&verifyServerCertificate=false&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.zyc.jobmanager.entity
  mapper-locations: classpath:mapper/*.xml

myprops:
  init_mode: 1
  init_begin: 2018-09-01
  init_end: 2018-09-30
  open-id: 7344c77f9a7f4f249bd9df04115171e6
  token:
  refresh_token:
  token_init: 6fb59584-a8c4-4218-9b5e-5e88edb46575
  expire_days: 2
  token_init_date: 2018-01-16 23:47
  redis_host: 59.110.169.156
  redis_port: 6379

